jobs:
  - job: "Windows"
    displayName: "Build and test Windows"
    pool:
      vmImage: windows-latest
    variables:
      pythonVersion: "3.9"

    steps:
      # Use a specific Python version
      - task: UsePythonVersion@0
        displayName: Use Python $(pythonVersion)
        inputs:
          versionSpec: $(pythonVersion)
          addToPath: true
          architecture: "x64"

      - script: |
          $ErrorActionPreference = 'Stop'
          $PSNativeCommandUseErrorActionPreference = $true
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          python --version
          where python
          mkdir build
          cd build
          cmake -DPython_FIND_REGISTRY=LAST ..
          whoami -xyzzy
          dir
        displayName: "Build and test"
