jobs:
  - job: "Windows"
    displayName: "Build and test Windows"
    pool:
      vmImage: windows-latest
    variables:
      pythonVersion: "3.9"
      cmakeBuildType: Release

    steps:
      # Use a specific Python version
      - task: UsePythonVersion@0
        displayName: Use Python $(pythonVersion)
        inputs:
          versionSpec: $(pythonVersion)
          addToPath: true
          architecture: "x64"
          ErrorActionPreference: "Stop"
          PSNativeCommandUseErrorActionPreference: true
      - task: BatchScript@1
        inputs:
          filename: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat'
          modifyEnvironment: true
      - powershell: |
          python --version
          where python
          mkdir build
          cd build
          Write-Host "CMAKE_BUILD_TYPE == $(cmakeBuildType)"
          Write-Host "CMAKE_BUILD_TYPE == $Env:cmakeBuildType"
          cmake -DCMAKE_BUILD_TYPE:STRING=$(cmakeBuildType) -DPython_FIND_REGISTRY=LAST ..
          dir
        displayName: "Build and test"
